title: bore
email: wbbr.ryan@gmail.com
description: >-
  A boring build file generator

baseurl: ""
url: "https://ryanwebber.github.io/bore/"
github_url:  "https://github.com/ryanwebber/bore"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

