title: bore
email: wbbr.ryan@gmail.com
description: >-
  A boring build file generator

baseurl: "/bore"
url: "https://ryanwebber.github.io"
github_url:  "https://github.com/ryanwebber/bore"

markdown: kramdown
theme: null

exclude:
  - Gemfile
  - Gemfile.lock

