name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v3
      with:
        luaVersion: "5.3.5"
    - name: test
      run: docker build .

